# Generated by Django 3.0.7 on 2020-06-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200605_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsSpec',
            new_name='Product',
        ),
    ]
